# Slapper hit delay in seconds, You can set the custom delay by editing the delay below
delay: 0.5
# Message to be displayed as a tip when a player attempts to hit a Slapper too quickly
message: "§cDon't slap me too fast please!"
